<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019\1\18 0018
 * Time: 11:30
 */

namespace app\admin\controller;

use app\common\controller\AdminBase;
use app\common\model\InsuranceCompany;
use app\common\model\Insured;
use app\common\model\Order;
use app\common\model\OrderExtra;
use app\common\model\PolicyHolder;
use app\common\model\Product;
use think\Db;
use app\common\model\AdminUser;
use app\common\model\Investor;

class Instalment extends AdminBase
{

    protected $adminId;
    protected $adminPid;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->adminId = session('admin_id');
        $this->adminPid = session('admin_pid');
    }

    //待审核申请
    public function index()
    {
        $data = $this->request->param();
        $admin_id = AdminUser::where('pid', $this->adminId)->column('id');
        $data['admin_id'] = $admin_id;
        $data['status'] = Order::STATUS_APPLY;
        $data = app('order')->search($data);
        return $this->fetch('index', ['data' => $data,'status'=>Order::$status]);
    }

    public function add()
    {
        $investor = Investor::all();
        $products = Product::all();
        $companys = InsuranceCompany::all();
        $areas = app('area')->getArea();
        return $this->fetch('add', ['products'=>$products,'investor'=>$investor,'companys'=>$companys,'areas'=>$areas]);
    }

    public function save()
    {
        if($this->request->isPost()) {
            $data = $this->request->param();
            Db::startTrans();
            try{
                //保存客户信息
                $data['admin_id'] = $this->adminId;
                if(isset($data['insured_id'])){
                    $data['id'] = $data['insured_id'];
                }
                $result = app('order')->saveInsured($data);
                if($result['code'] != 0){
                    throw new \Exception($result['msg']);
                }
                unset($data['id']);
                $product = Product::get($data['product_id']);
                if(empty($product)){
                    throw new \Exception('分期产品不存在');
                }
                $data['stage'] = $product->stage;
                $data['repayment'] = $product->charge;
                $data['type'] = Order::TYPE_INSURANCE;
                //保存订单
                $data['insured_id'] = $insured_id = $result['data']['id'];
                if(isset($data['order_id'])){
                    $data['id'] = $data['order_id'];
                }
                $result = app('order')->saveOrder($data);
                if($result['code'] != 0){
                    throw new \Exception($result['msg']);
                }
                unset($data['id']);
                //保存订单扩展信息
                if(isset($data['order_id'])){
                    $data['id'] = OrderExtra::where('order_id', $data['order_id'])->value('id');
                }
                $data['order_id'] = $order_id = $result['data']['id'];
                $result = app('order')->saveOrderExt($data);
                if($result['code'] != 0){
                    throw new \Exception($result['msg']);
                }
                //保存投保车辆信息
                $result = app('order')->saveCar($data);
                if($result['code'] != 0){
                    throw new \Exception($result['msg']);
                }
                unset($data['id']);
                Db::commit();
                $this->success($result['msg'], 'Instalment/index');
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }
        }
    }

    public function subsist()
    {
        $products = Product::all();
        $companys = InsuranceCompany::all();
        $areas = app('area')->getArea();
        return $this->fetch('addsubsist', ['products'=>$products,'companys'=>$companys,'areas'=>$areas]);
    }

    //根据手机号查询客户信息
    public function getcustomer($mobile)
    {
        if($mobile && strlen($mobile) == 11){
            $data = app('order')->getInsuredByMobile($mobile);
            $this->result($data);
        }
        $this->result('手机号错误', 1);
    }

    public function getpolicy($investor_id)
    {
        $data = PolicyHolder::where('investor_id', $investor_id)->select();
        $this->result($data);
    }

    //行驶证识别
    public function license($imageUrl)
    {
        if($imageUrl) {
            $aipOcrService = app('baidu')->getAipOcrInstance();
            $result = $aipOcrService->vehicleLicense($imageUrl);
            $this->result($result);
        }
        $this->result('参数错误');
    }

    //识别身份证
    public function idcard($imageUrl)
    {
        if($imageUrl) {
            $aipOcrService = app('baidu')->getAipOcrInstance();
            $result = $aipOcrService->idcard($imageUrl);
            $this->result($result);
        }
        $this->result('参数错误');
    }

    //识别营业执照
    public function businessLicense($imageUrl)
    {
        if($imageUrl) {
            $aipOcrService = app('baidu')->getAipOcrInstance();
            $result = $aipOcrService->idcard($imageUrl);
            $this->result($result);
        }
        $this->result('参数错误');
    }

    //客户列表
    public function customer(Insured $insured)
    {
        $data = $this->request->param();
        $query = $insured->withSearch(['keyword', 'sort'], [
            'custom' => 'name|mobile',
            'keyword' => $data['keyword'] ?? '',
            'sort' => ['id' => 'desc']
        ]);

        $admin_id = $this->adminId;
        if($this->adminPid == 0){
            $admin_id = AdminUser::where('pid', $this->adminId)->column('id');
        }
        $query->where(['admin_id' => $admin_id]);
        $data = $query->paginate($this->size, false, array_query($data));
        return $this->fetch('customer', ['data' => $data]);
    }

    //分期申请查询
    public function apply()
    {
        $data = $this->request->param();
        $admin_id = $this->adminId;
        if($this->adminPid == 0) {
            $admin_id = AdminUser::where('pid', $this->adminId)->column('id');
        }
        $data['admin_id'] = $admin_id;
        $data['type'] = Order::TYPE_INSURANCE;
        $data = app('order')->search($data);
        return $this->fetch('apply', ['data' => $data,'status'=>Order::$status]);
    }

    //存续车险验真
    public function verify()
    {
        $data = $this->request->param();
        $admin_id = $this->adminId;
        if($this->adminPid == 0) {
            $admin_id = AdminUser::where('pid', $this->adminId)->column('id');
        }
        $data['admin_id'] = $admin_id;
        $data['type'] = Order::TYPE_INSURANCE;
        $data['is_renewal'] = Order::RENEWAL_TRUE;
        isset($data['start_time']) && $data['start_time'] && $data['start_time'] = strtotime($data['start_time']);
        isset($data['end_time']) && $data['end_time'] && $data['end_time'] = strtotime($data['end_time']);
        $data = app('order')->search($data);
        return $this->fetch('verify', ['data' => $data,'status'=>Order::$status]);
    }

}