<?php
namespace app\common\model;

use think\facade\Config;

/**
 * 管理员模型
 * Class AdminUser
 *
 * @package app\common\model
 */
class AdminUser extends Base
{
    protected $type = [
        'last_login_time' => 'timestamp'
    ];

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        self::beforeDelete(function ($model) {
            if (intval($model->id) === 1) {
                $model->error = '默认管理员不可删除';
                return false;
            }
        });

        $session = app()->session;

        //登录用户为经销商
        if ($session->get('admin_group_id') === AuthGroup::DEALER) {
            self::beforeWrite(function ($model) use ($session) {
                $model->appendData(['pid' => $session->get('admin_id')]);
            });
        }
    }

    /**
     * 权限组关联
     * @return \think\model\relation\BelongsToMany
     */
    public function authGroup()
    {
        return $this->belongsToMany('AuthGroup', 'AuthGroupAccess', 'group_id', 'uid');
//        return $this->belongsTo('AuthGroup', 'group_id', 'id');
    }

    /**
     * 设置密码
     * @param $value
     * @param $data
     *
     * @return string
     */
    public function setPasswordAttr($value, $data)
    {
        return md5($value . Config::get('salt'));
    }
}
