<?php
namespace app\common\model;

/**
 * 权限组
 * Class AuthGroup
 *
 * @package app\common\model
 */
class AuthGroup extends Base
{
    const SUPER = 1;
    const DEALER = 2;
    const ADMIN = 3;

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::beforeUpdate(function ($model) {
            if (isset($model['status'])) {
                if (in_array($model->id, self::getDefault()) && intval($model->status) !== 1) {
                    $model->error = '默认权限组不能禁用';
                    return false;
                }
            }
        });
        self::beforeDelete(function ($model) {
            if (isset($model['status'])) {
                if (in_array($model->id, self::getDefault()) && intval($model->status) !== 1) {
                    $model->error = '默认权限组不能删除';
                    return false;
                }
            }
        });
    }

    /**
     * 获取默认权限组
     * @return array
     */
    public static function getDefault()
    {
        return [self::SUPER, self::DEALER, self::ADMIN];
    }

    /**
     * 获取权限组
     * @return array|\PDOStatement|string|\think\Collection
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getLists()
    {
        //经销商
        if (intval(app()->session->get('admin_group_id')) === self::DEALER) {
            return self::whereNotIn('id', self::getDefault())->select();
        }

        //不返回超级管理员权限组
        return self::where('id', 'neq', self::SUPER)->select();
    }
}