<?php

namespace app\common\model;

/**
 * 保险公司
 * Class InsuranceCompany
 *
 * @package \app\common\model
 */
class InsuranceCompany extends Base
{
    const STATUS_APPLY = 1;
    const STATUS_PASS = 2;
    const STATUS_REJECT = 0;
////    const STATUS_PENDING = 4;
//    const STATUS_ACTIVE = 5;

    public static $status = [
        self::STATUS_APPLY => '待审核',
        self::STATUS_PASS => '已通过',
        self::STATUS_REJECT => '未通过',];
//        self::STATUS_PENDING => '待认证',
//        self::STATUS_ACTIVE => '保单生效',];

    protected static function init()
    {

        parent::init(); // TODO: Change the autogenerated stub

        $session = app()->session;

        self::afterDelete(function ($info) {
            /**
             * @var  \app\common\model\InsuranceCompany $info
             */
            //删除经济公司
            $info->ibec()->where(['company_id'=>$info['id']])->delete();
        });

        //登录用户为经销商
//        if ($session->get('admin_group_id') === AuthGroup::DEALER) {
            self::beforeWrite(function ($model) use ($session) {
                $model->appendData(['admin_id' => $session->get('admin_id')]);
            });
//        }
    }

    /**
     * 经济公司
     * @return \think\model\relation\HasMany
     */
    public function ibec()
    {
        return $this->hasMany('Ibec', 'company_id', 'id');
    }
}