<?php

namespace app\common\controller;

use think\Controller;
use think\exception\HttpResponseException;
use think\Response;

/**
 * Class ApiBase
 *
 * @package \app\common\controller
 */
class ApiBase extends Controller
{
    protected $page = 1;
    protected $size = 10;

    protected $token = '';

    protected $user = '';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //移除HTML标签
        $this->request->filter('strip_tags');

        // token
        $this->token = $this->request
            ->server('HTTP_TOKEN', $this->request->request('token', app()->cookie->get('token')));

        $this->user = $this->app->cache->get($this->token);

       /* if (!$this->token || !$this->user) {
            $this->redirect('/');
        }*/
        /*
         * 加载分页
         */
        $this->page = $this->request->param('page', 1);
        $this->size = $this->request->param('size', 10);
    }

    /**
     * 返回封装后的API数据到客户端
     * @access protected
     * @param  mixed     $data 要返回的数据
     * @param  integer   $code 返回的code
     * @param  mixed     $msg 提示信息
     * @param  string    $type 返回数据格式
     * @param  array     $header 发送的Header信息
     * @return void
     */
    protected function result($msg, $code = 0, $data = null, $type = '', array $header = [])
    {
        if (is_array($msg)) {
            $result = $msg;
            $result['time'] = time();
        } else {
            $result = [
                'code' => $code,
                'msg'  => $msg,
                'time' => time(),
                'data' => $data,
            ];
        }

        $type     = 'json';

        $response = Response::create($result, $type)->header($header);

        throw new HttpResponseException($response);
    }

    /**
     * 获取用户信息
     */
    public function getUser()
    {
        return json_decode($this->user);
    }
}
