<?php

namespace app\index\controller;

use app\common\controller\IndexBase;
use app\index\service\Verify;

/**
 * 保单
 * Class Order
 *
 * @package \app\index\controller
 */
class Order extends IndexBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        bind('verify', Verify::class);
    }

    /**
     * @title 验证页面@
     * @return \think\response\View
     */
    public function verify(\app\common\model\Order $order)
    {
        $this->assign('info', $order);
        return view();
    }

    /**
     * @title 合同签署@
     */
    public function contract(\app\common\model\Order $order)
    {
        $this->assign('info', $order);

        return view('contract');
    }

    /**
     * 合同签署
     */
    public function contractVerify(\app\common\model\Order $order)
    {
        $this->app->verify->contract($order);
    }

    /**
     * 银行卡签约发送短信
     */
    public function bankSend(\app\common\model\Order $order)
    {
        $this->app->verify->bankSend($order);
    }

    /**
     * 银行卡签约
     */
    public function bankcardVerify(\app\common\model\Order $order)
    {
        $this->app->verify->bankcard($order);
    }
}