<?php

namespace app\index\controller;

use app\common\controller\IndexBase;
use app\common\model\Tonglian;
use app\common\service\PayService;

/**
 * 支付
 * Class Pay
 *
 * @package \app\api\controller
 */
class Pay extends IndexBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $param = $this->request->param();

        array_shift($param);

        $this->app->bindTo('pay', new PayService($param));
    }

    /**
     * 批量支付
     */
    public function pays()
    {
        $result = app()->pay->signPays();

        exit();
//        $this->result($result);
    }

    /**
     * 发送签约短信
     */
    public function sendBind()
    {
        $result = app()->pay->sendBind();

        $this->result($result);
    }

    /**
     * 银行卡签约
     */
    public function bind()
    {
        $result = app()->pay->bind();

        $this->result($result);
    }

    /**
     * 银行卡解约
     */
    public function unbind()
    {
        $result = app()->pay->unbind();

        $this->result($result);
    }

    /**
     * 签约支付
     */
    public function pay()
    {
        $result = app()->pay->signPay();

        $this->result($result);
    }

    /**
     * 交易结果查询
     */
    public function search()
    {
        $result = app()->pay->search();

        $this->result($result);
    }

    /**
     * 退款
     */
    public function refund()
    {
        $result = app()->pay->refund();

        $this->result($result);
    }
}