<?php

namespace app\api\controller;

use think\Controller;

/**
 * Class Login
 *
 * @package \app\api\controller
 */
class Login extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $token = $this->request
            ->server('HTTP_TOKEN', $this->request->request('token', app()->cookie->get('token')));

        $user = $this->app->cache->get($token);

        if ($user) {
            $this->redirect(url('/user'));
        }
    }

    /**
     * 登录
     */
    public function login()
    {
        return view('login');
    }

    /**
     * 注册
     */
    public function register()
    {
        return view('register');
    }

    /**
     * 验证登录
     */
    public function check()
    {
        $param = $this->request->param();


    }

    /*
     * 验证注册
     */
    public function checkRegister()
    {

    }
}